---
- name: Hosts resoursec
  hosts: node1
  become: yes

  tasks:        
    - name: Get CPU usage 
      shell: "top -b -n 1" 
      register: top 

    - name: Set CPU usage facts 
      set_fact: 
        user_cpu: "{{top.stdout_lines[2].split()[1]}}" 
        system_cpu: "{{top.stdout_lines[2].split()[3]}}" 


    - name: Print info about RAM
      debug:
        msg: 
          - Total RAM is {{ ansible_memory_mb.real.total }} MB
          - Free RAM is  {{ ansible_memory_mb.nocache.free }} MB
          - Free RAM without cached RAM {{ ansible_memory_mb.real.free }}

    - name: Print info about disk space
      debug: 
        msg:
          - "Free space {{ (((item.size_available/1024)/1024)/1024)|round(2,'common') }} GB"
          - "Total space {{ (((item.size_total/1024)/1024)/1024)|round(2,'common') }} GB"
      loop: "{{ ansible_mounts | list }}"
      loop_control:
         label: "{{ item.mount }}"
    
 
    - name: Output CPU usage facts 
      debug: 
        msg: 
          - "User CPU usage: {{user_cpu}} % CPU time spent in user space" 
          - "System CPU usage: {{system_cpu}} % CPU time spent in kernel space" 